# disk cleaner script
import os
import time
from tkinter import messagebox

def disk_cleaner_server():
    print("Disk Cleaner")
    print("============")
    print("This script will clean up the disk space on this machine.")
    print("It will remove the following:")
    print("- Windows Update Files")
    print("- Windows Error Reporting Files")
    print("- Windows Log Files")
    print("- Windows Temp Files")
    print("- Windows Temp Internet Files")
    print("- Windows Temp Update Files")
    print("- Windows Temp Error Reporting Files")
    print("- Windows Temp Log Files")
    print("- Windows Temp Internet Files")
    print("- Windows Temp Update Files")
    print("- Windows Temp Error Reporting Files")
    print("- Windows Temp Log Files")
    print("- Windows Temp Internet Files")
    print("- Windows Temp Update Files")
    print("- Windows Temp Error Reporting Files")
    print("- Windows Temp Log Files")
    print("- Windows Temp Internet Files")
    print("- Windows Temp Update Files")
    print("- Windows Temp Error Reporting Files")
    print("- Windows Temp Log Files")
    print("- Windows Temp Internet Files")
    print("- Windows Temp Update Files")
    print("- Windows Temp Error Reporting Files")
    print("- Windows Temp Log Files")
    print("- Windows Temp Internet Files")
    print("- Windows Temp Update Files")
    print("- Windows Temp Error Reporting Files")
    print("- Windows Temp Log Files")
    print("- Windows Temp Internet Files")
    print("- Windows Temp Update Files")
    print("- Windows Temp Error Reporting Files")
    print("- Windows Temp Log Files")
    print("- Windows Temp Internet Files")
    print("- Windows Temp Update Files")
    print("- Windows Temp Error Reporting Files")
    print("- Windows Temp Log Files")
    print("- Windows Temp Internet Files")
    print("- Windows Temp Update Files")
    print("- Windows Temp Error Reporting Files")
    print("")

    print("This script will take a while to complete.")
    print("Please be patient.")
    print("")

    print("Press Enter to continue.")
    input()

    print("Cleaning up Windows Update Files...")
    time.sleep(1)
    os.system('del /f /s /q /a %windir%\SoftwareDistribution\Download\*.* >nul 2>&1')
    print("Cleaning up Windows Error Reporting Files...")
    time.sleep(1)
    os.system('del /f /s /q /a %windir%\System32\winevt\Logs\*.* >nul 2>&1')
    print("Cleaning up Windows Log Files...")